INSERT INTO VETERINARIAS (ID_VETERINARIA, NOMBRE, DIRECCION, TELEFONO)
VALUES(1,'LUNA-VET','COLOSO INFONAVIT, AVENIDA LAS TORRES ESTAPA 38',7442130868);
INSERT INTO VETERINARIAS (ID_VETERINARIA, NOMBRE, DIRECCION, TELEFONO)
VALUES(2,'VET-CENTER','COLOSO INFONAVIT,CARR, CAYACO PUERTO MARQUÉS',7442383376);
INSERT INTO VETERINARIAS (ID_VETERINARIA, NOMBRE, DIRECCION, TELEFONO)
VALUES(3,'VETERINARIA DR. NÁJERA','C. ALMTE. PEARY 18 B, COSTA AZUL 39850 ',7444322674);