--SE ELIMINA UNA TABLA SIMILIAR SI ES QUE EXISTE
DROP TABLE IF EXISTS VETERINARIAS;
-----------------------------------------------
CREATE TABLE VETERINARIAS(
	ID_VETERINARIA NUMBER,
	NOMBRE NVARCHAR2(100),
	DIRECCION NVARCHAR2(100),
	TELEFONO NUMBER,
	CONSTRAINT ID_VETERINARIA_PK PRIMARY KEY(ID_VETERINARIA)
	
);