INSERT INTO CLIENTESM(ID_CLIENTESM,NOMBRE,DIRECCION,CONTACTO)
VALUES(1,'DANIEL DE LA CRUZ','DEL CEREZO,ACAPULCO GUERRERO',7441512032);
INSERT INTO CLIENTESM(ID_CLIENTESM,NOMBRE,DIRECCION,CONTACTO)
VALUES(2,'FLOR DE JESUS','CHARLLOTE USA',1221512032);
INSERT INTO CLIENTESM(ID_CLIENTESM,NOMBRE,DIRECCION,CONTACTO)
VALUES(3,'ANDREA MICHEL V','CAMPESTRE DE LA LAGUNA',7441746457);
INSERT INTO CLIENTESM(ID_CLIENTESM,NOMBRE,DIRECCION,CONTACTO)
VALUES(4,'EMANUEL T','FUENTES DEL MAUREL 1,L ACAPULCO.GRO',7431512032);
INSERT INTO CLIENTESM(ID_CLIENTESM,NOMBRE,DIRECCION,CONTACTO)
VALUES(5,'SAMUEL REYNADA','AV.UNIVERCIDAD, GRO.',7443552032);
